version: "3"
services:
    database:
        container_name: mysqldb
        image: mysql:8.3.0
        environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
        - 3306:3306
    app:
        depends_on:
        - database
        container_name: api-learning
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
        -  .:/var/www/html
        ports:
        - 9000:9000
    nginx:
        image: nginx:latest
        ports:
        - "8000:80"
        volumes:
        - .:/var/www/html
        - ./nginx:/etc/nginx/conf.d
        depends_on:
        - app

